### PR TITLE
Added data/MSC01_grayplot_data.mat to git-annex

### PR DESCRIPTION
**Pull request by yarikoptic**
I just pointed annex to your box on dropbox per url you provided.  so now anyone who clones my fork could use git-annex to fetch that file from there (should have done that to other .mat files as well to minimize impact on .git/objects and cloning time ;) ):
```shell
$> git clone https://github.com/yarikoptic/DartmouthMIND_tutorial           
Cloning into 'DartmouthMIND_tutorial'...                         
remote: Counting objects: 161, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 161 (delta 35), reused 160 (delta 34), pack-reused 0
Receiving objects: 100% (161/161), 186.33 MiB | 5.30 MiB/s, done.
Resolving deltas: 100% (35/35), done.

$> cd DartmouthMIND_tutorial/data/                       

$> git annex get MSC01_grayplot_data.mat     
get MSC01_grayplot_data.mat (from web...) 
mp/DartmouthMIND_tut  27%[++++>               ] 115.25M  6.37MB/s  
```
or just in one datalad call
```
datalad install -g https://github.com/yarikoptic/DartmouthMIND_tutorial 
```

- there is also `git-annex`  branch in my fork now which you would need to pick up from my clone (let me know if you need help with that)
- later I could add a clone to be distributed also through that collection at http://datasets.datalad.org/?dir=/workshops/mind-2017  may be even mirroring that file for extra redundancy ;)

### CODE REVIEW

**Comment by yarikoptic** [comment]
so what is left is to push the state of my git-annex branch (contains information about where data files is available from) into your repository.  unfrotunately github does not allow for PR without a merge into a new branch, so could you run following manually? (in case you don't have git-annex installed)
```shell
git remote add gh-yarikoptic https://github.com/yarikoptic/DartmouthMIND_tutorial
git fetch gh-yarikoptic  # this should fetch my git-annex branch
git push origin gh-yarikoptic/git-annex:git-annex    # this should push it into your repository
```

**Comment by cgratton** [comment]
Hmm. I merged the previous commit, but when I also tried to do the manual pieces you suggested, I got the following error on the final piece:
```

git push origin gh-yarikoptic/git-annex:git-annex
error: unable to push to unqualified destination: git-annex
The destination refspec neither matches an existing ref on the remote nor
begins with refs/, and we are unable to guess a prefix based on the source ref.
error: failed to push some refs to 'git@github.com:cgratton/DartmouthMIND_tutorial.git'
```

Is there anything else I should be doing? I haven't used either git-annex or datalad before.

**Comment by yarikoptic** [comment]
sorry for the delay and incomplete instructions
1. disclaimer: it is all a bit awkward since I am actually trying to avoid you needing to install git-annex for this.  If you had it installed, you should have done `git annex init; git annex merge; git push origin git-annex`
2. confession: I just thought that I am so knowledgeable already that I haven't tried to run this first myself ;)  apparently I did not know about this catch "The destination refspec neither matches an existing ref"  
3. solution: the command should have been `git push origin gh-yarikoptic/git-annex:refs/heads/git-annex` apparently to disambiguate some magic ;) (I did try on a similar case this time locally and it seemed to work ;) )

**Comment by cgratton** [comment]
Great - that seems to have worked.  I'll likely make a few final changes to the code tomorrow to do final preps for the tutorial. I'll let you know when that's ready. Thanks again for your help.

**Pull request merged**
